(setq notmuch-saved-searches '((:name "inbox"
										:key "i"
										:query "tag:inbox"
										:count-query "tag:inbox"
										:sort-order newest-first
										:search-type tree)
								 (:name "unread"
										:key "u"
										:query "tag:unread"
										:count-query "tag:unread"
										:sort-order oldest-first)
								 (:name "sent"
										:key "s"
										:query "tag:sent"
										:count-query "tag:sent"
										:sort-order newest-first
										:search-type tree)
								 (:name "school"
										:key "c"
										:query "tag:school"
										:count-query "tag:school"
										:sort-order newest-first)
								 (:name "deleted"
										:key "d"
										:query "tag:delete"
										:count-query "tag:delete"
										:sort-order newest-first)
								 (:name "all"
										:key "a"
										:query "*"
										:count-query "*"
										:sort-order newest-first
										:search-type tree)
								 (:name "receipts"
										:key "r"
										:query "tag:receipt"
										:count-query "tag:receipt"
										:sort-order newest-first
										:search-type tree)
								 (:name "trash"
										:query "tag:trash OR tag:delete"
										:count-query "tag:trash OR tag:delete OR tag:spam"
										:sort-order oldest-first)
								 (:name "important"
										:key "p"
										:query "tag:important"
										:count-query "tag:important"
										:sort-order newest-first)
								 (:name "holiday"
										:query "tag:holiday"
										:count-query "tag:holiday"
										:sort-order newest-first)
								 (:name "events"
										:query "tag:event"
										:count-query "tag:event"
										:sort-order newest-first)
								 (:name "drafts"
										:query "tag:draft"
										:count-query "tag:draft"
										:sort-order oldest-first)))
